# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('pc_num', models.IntegerField(db_column='PC_Num', primary_key=True, serialize=False)),
                ('floor_num', models.IntegerField(blank=True, db_column='Floor_Num', null=True)),
            ],
            options={
                'db_table': 'pc',
                'managed': False,
            },
        ),
    ]
