# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_num', models.IntegerField(db_column='Floor_Num', primary_key=True, serialize=False)),
                ('floor_name', models.CharField(blank=True, db_column='Floor_name', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='Reservation_ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('id_year', models.CharField(blank=True, db_column='ID_Year', max_length=3, null=True)),
                ('college', models.CharField(db_column='College', max_length=3)),
                ('patron', models.CharField(db_column='Patron', max_length=45)),
                ('datetime_stamp', models.DateTimeField(blank=True, db_column='DateTime Stamp', null=True)),
                ('datetime_start', models.DateTimeField(blank=True, db_column='DateTime Start', null=True)),
                ('duration', models.IntegerField(db_column='Duration')),
            ],
            options={
                'managed': False,
                'db_table': 'reservation',
            },
        ),
    ]
